### ISSUE TITLE
Ctrl+C should discard current input

### ISSUE THREAD

**Issue by stefanofornari** [stefanofornari/BshConsole#2]
As opposed to exit the shell

**Comment by nickl-** [comment]
+1

**Comment by nickl-** [comment]
The awesome demo does this perfectly should be easy... lol =D

**Comment by nickl-** [comment]
I found this explanation on how this should be done, so I proceeded to implement it. Turns out it was not that complicated and we were already most of the way there.

Leaving this write up here just in case... you never know.


You can use ^C, ^Z to interrupt or put jobs in the background.

Basically, what you need to do is to call TerminalBuilder#nativeSignals and use TerminalBuilder#signalHandler(SignalHandler.SIG_IGN)  to make sure the ^C is caught.
then on the terminal, you'll be able to register a handler using the Terminal#handle method and interrupt the job which is running.
https://github.com/jline/jline3/blob/master/terminal/src/main/java/org/jline/terminal/TerminalBuilder.java

```java
public class Main {
  private static AtomicBoolean running = new AtomicBoolean(true);

  public static void main(String[] args) throws Exception {
    Terminal terminal = TerminalBuilder.builder()
      .nativeSignals(true)
      .signalHandler(Terminal.SignalHandler.SIG_IGN)
      .build();

    Terminal.SignalHandler interruptHandler = terminal.handle(Terminal.Signal.INT, s -> {
      running.set(false);
    });

    LineReader reader = LineReaderBuilder.builder()
      .terminal(terminal)
      .build();

    try {
      while (running.get()) {
        String line = reader.readLine("Enter command> ");
        if (line.equals("start")) {
          System.out.println("Endless loop started...");
          endless(); // Here: capture Ctrl+C to stop endless()
          System.out.println("Loop canceled");
        }
        else {
          System.out.println("bye");
          running.set(false);
        }
      }
    }
    finally {
      terminal.handle(Terminal.Signal.INT, interruptHandler);
    }
  }

  private static void endless() throws InterruptedException {
    int i = 1;
    while (running.get()) {
      System.out.println("waiting " + i);
      i++;
      Thread.sleep(1000);
    }
  }
}
```

**Comment by stefanofornari** [comment]
Hi nick,

thanks for looking into this, but this was not my problem :) I am already
sucessfully intercepting Ctrl+C and for now I am exiting the shell. But
this is not what I want. I prefer that on Ctrl+C what I have written so far
is discarded and I would like a way in beanshell to nicely discard the
nodes parsed so far. The use case is as follows: you write a bunch of line
of code and you realize you want to start from scratch... you can delete
the last line, but what about the onces already fed into beanshell?
I sow something like a reset in the parser class, I will look into it.

Thanks for the other feedbacks too. I will reply later.

Ste

**Comment by nickl-** [comment]
=) It now does what you describe... great minds think alike.

The state is preserved: any variables set or functions/classes created prior to the interrupt is preserved by creating the new interpreter with the interrupted interpreter as its parent. We are even able to interrupt infinite loops...

To interrupt/reset interpreter you can force an EOF by closing the input.
By default interpreter will exit the VM on EOF, unless you make `exitOnEOF = false`, it always exits on EOF but now the VM keeps running and we can create a new thread preserving the context.

Nothing needed to change in beanshell to make this work but I did make some enhancements to improve the usage. 
Beanshell does not have to print the banner again, when created with a parent interpreter. Without this change you will see the banner printed every time after a interrupt.
We cannot force threads to stop/die in java anymore... we can only interrupt them which sets `Thread.interrupted = true`. We can make our loops aware of this so that they abort quicker when the thread is interrupted. Without this change the loops will take longer to die and keep changing the state while running... for example:

```
bsh % a = 25;
--> 25
bsh % while (true) a++;
^C
bsh % a;
--> 345345
bsh % a = 25;
--> 25
bsh % a;
--> 131234 // interrupted thread is still running
bsh %
```

The long and short: #8 should work without any changes to beanshell but I made some changes to improve this use case.

**Comment by stefanofornari** [comment]
great! thanks!

Ste

**Comment by stefanofornari** [comment]
@nick, please my comments on your PR and my PR :)

**Comment by stefanofornari** [comment]
I still need to fix the parser error while discarding content, but I need first to see if the PR goes into Beanshell.

**Comment by nickl-** [comment]
I think we have a communication gap. =(

I thought since you merged the #8 you don't need the reset parser patch anymore, they kind of do the same thing don't they? My apologies if I was keeping you up... why do you need the patch?

**Comment by stefanofornari** [comment]
Hi Nick,

I tried to comment the pr, but maybe I haven't done it right... :(

Here is why I would like to address it differently:

I see two issues with this apporach:

   1. when you type ^C, a parser error is thrown; understandable, but not
   super-nice :)
   2. it is a bit overweighted for the task; but based on your idea, I
   worked on another approach which requires a little change to Interpreter;
   please see beanshell/beanshell#75
   <https://github.com/beanshell/beanshell/pull/75>

I hope this clarifies it.


Ste

**Comment by nickl-** [comment]
>   1. when you type ^C, a parser error is thrown; understandable, but not super-nice :)

Why do you want to type `^` and `C` followed by `Enter`? I don't understand? The only way you should produce an interrupt, a ^C, is by pressing the Ctrl and C keyboard keys simultaneously. My patch will echo "^C" to stdout. There will be nothing to parse, infact the parser gets interrupted and restarted.

If you do type the `^` and `C` for the BeanShell parser t parse there is absolutely no grammar that supports that, if we do add extra complexity to the grammar so that the parser can parser "^C" how should that text be interpreted as beanshell script then? What other than a parser error do you expect? Why would you want to type ^C? What do you want it to mean? 

It cannot be translated to an interrupt or SIGHUB signal if that is what you were going for. Typing ^ and C instead of Ctrl and C or maybe creating a cttrlc.bsh with the text ^C to be executed. Ctrl + C is not a command or execution it is a signal generated by the operating system there is absolutely no way to fake it. You'll probably have more luck programatically operating the power switch. 

I am probably misunderstanding you again =( apologies in advance.

Would it perhaps help if we didn't print "^C" at all? ...completely removing it from the equation? I am confused... =/

I did try your patch but couldn't get it to do anything for me. `resetParser` just stops the interpreter what is supposed to happen after that? I elaborated on the issue.

Hahah I got it... we can simply remove the ^ and C keys that would fix it hehehehe. Jus joking...

You got to help me out here man.

**Comment by nickl-** [comment]
Have you actually tried the pressing the Ctrl and C keys simultaneously?

try this in a beanshell session.

Type the following.

while(true) 1+1;

You will not be able to type anything else after you pressed enter. But if you press Ctrl and C together it will exit the while loop and beanshell will print "^C" followed by a beanshell prompt. Now you can type again, and we didn't exit the shell. Wasn't that what we wanted?

I'm grasping at straws here... wish I could help.

**Comment by nickl-** [comment]
You can also SIGKILL with ^Z just fyi

**Comment by stefanofornari** [comment]
Hi Nick,

now I understand the misunderstanding... :)

with "type ^C" I meant Ctrl+C

My point is that it should not force a parsing error, it should just
discard the current input. I am moving the other discussion (
https://github.com/beanshell/beanshell/pull/75).

>>>>

Currently the steps include: (not necessarily in order)

   - Interrupt running thread
   - turn exit on EOF off (very very NB or there's not much point in ever
   trying any of this)
   - close input and trigger EOF
   - initialise new input
   - initialise new interpreter (adding old interpreter as parent to retain
   state)
   - start new thread REPL

But it just seems awkward to expect Interpreter to handle this for itself,
doesn't it? Perhaps a Runner or similar helper would feel more natural, I
just can't help but feel this functionality resides externally.

<<<<<

I guess we agree on the fact that this approach smells. I do also agree the
functionality must be handled externally, but Parser or Interpreter then
have to support it. Let's do a step back and focus what we really need:

we need that for any external reasons, we are able to discard the content
parsed so far and restart from scratch reading the content.

the only way I found so far was to close the stream so that the current
parser fails (that is why catching TokenMgrException was needed) and
recreate the Parser which is still easier than the above. But to me there
should be a simple call to the parser to reset its status. This would be
the cleanest solution. Only, I do not know how to exactly do it... I am not
too deep in the understanding of jjtree ... :(

At minimum, maybe that for now you could make some of the relevant private
members protected, so that I can do most of the work in a subclass of
bsh.Interpreter. What do you think?

Or maybe I should just create my own version of Interpreter, so that you
can see better than how I can explain what it is needed by an external
program to integrate bsh.Interpreter.


Ste

**Comment by nickl-** [comment]
oh ok, i c

The confusion came from the fact that Ctrl + C didn't give me a parser error, I looked. Where as "^C" does produce a parser error every time.

```
// Error: Parser Error: In file: <unknown> Encountered  "^" ^  at line 1, column 1.
```

As far as I can see Ctrl+C only produces an exception when aborting a multiline entry midway. 

This is the only message I can find:
```
// Error: Parser Error: In file: <unknown> Encountered <EOF> at line 1, column 6.
```

Please confirm that this is also the only parser error you found produced by Ctrl+C.

**Comment by nickl-** [comment]
Updated interpreter to prevent EOF parser exceptions in interactive mode.

This should resolve the issue.

**Comment by nickl-** [comment]
>  But to me there should be a simple call to the parser to reset its status. This would be the cleanest solution. Only, I do not know how to exactly do it... I am not too deep in the understanding of jjtree ...

I tried before to explain how the parser works, lets try again.

As you know the parser has the InputStream (`new Parser(in);`) and processes it one character at a time in forward mode only and attempts to apply the grammar (jjtree) to what it finds. On success it produces a hierarchy of node classes (all the BSH prefixed classes in the bsh package which all extends SimpleNode) which `Interpreter` then evaluates one hierarchy at a time during the REPL process.

excerpt from the run method:

```java
SimpleNode node = (SimpleNode)(get_jjtree().rootNode());
Object ret = node.eval( callstack, this );
```

What you are thinking makes perfect sense but as you can see that is not how the parser works. By the time we interrupt (Ctrl+C) all previous nodes were already parsed, nodes initialised and nodes evaluated there is nothing buffered in the parser or interpreter for us to reset or roll back.

Does this make more sense now?

Some more background which may be helpful:

These node evaluations is where the magic happens and how we implement the BeanShell language. Turning the text that was typed in which the parser made nodes from that represent the language constructs defined in the grammar, gets evaluated by equivalent java routines as per the node type to produce the desired functionality. 

These node evaluations uses the `NameSpace` which stores `Variable` and `BshMethod` classes in separate collections establishing references. Variables can get or set value based on type and methods can be invoked which in turn evaluates their block nodes. A hierarchy of name spaces establish scope, children can find references from parents but shelter their own references from parent and other children for example method arguments and local variables cannot be accessed from external name spaces.

We use byte code to generate classes (or interfaces or enums) which then perform like equivalent java entities, for example they can be instantiated, inherited from or implemented etc, but they are only similar in form. 

Each class has both a static and an instance name space which again stores their variables and methods. The static namespace gets evaluated as part of the class's static initialization (`<clinit>` a custom `static { }` block) which establishes class static state and instance name spaces are evaluated as part of the classes construction (`<init>` a custom instance block `{ }`) to establish instance state and also evaluates the appropriate constructor (still only a `BshMethod`) block node. Once initialised subsequent access to class references are provided by the name space collections, variables can get and set value and method invocation evaluates their individual block nodes where scope is established through another name space hierarchy. 

And that is BeanShell in a nut shell.

Make sense? Any questions?

**Comment by nickl-** [comment]
> Currently the steps include: (not necessarily in order)
>
>   - Interrupt running thread
>   - turn exit on EOF off
>   - close input and trigger EOF
>   - initialise new input
>   - initialise new interpreter (adding old interpreter as parent to retain state)
>   - start new thread REPL
>
> I guess we agree on the fact that this approach smells.

Smells like what? There are many kinds of code smells but non of which I am able to apply to this. I don't think we are in agreement.

Perhaps we need to break it down more.

To start interpreter requires the following steps.

  - Start interpreter:
    - initialise new input
    - initialise new interpreter
    - start new thread REPL

To manually stop interpreter requires the following steps

  - Stop Interpreter
    - Interrupt running thread
    - turn exit on EOF off
    - close input and trigger EOF

The steps required to implement Ctrl+C:

  - Stop Interpreter
  - Start interpreter


> I do also agree the functionality must be handled externally, but Parser or Interpreter then
have to support it.

The reason I am saying the functionality needs to be handled **externally** is because the initialization of the input as well as starting and stopping of the REPL thread, which is required to start and stop the interpreter are references held outside of the interpreter class (by the class instantiating the interpreter) Perhaps something like a Runner...

```java
class InterpreterRunner {
    public void startInterpreter() { }
    public void stopInterpreter() { }
    public void restartInterpreter() { }
}
```

> Or maybe I should just create my own version of Interpreter, so that you can see better than how I can explain what it is needed by an external program to integrate bsh.Interpreter.

Interpreter already supports both stopping and starting so I can't see what functionality is still required. But that's only my 2cents, I look forward to seeing what you have in mind.

**Comment by stefanofornari** [comment]
Thanks for the explanation.
I do think that we are looking at the wrong spot. The whole point is to be able to stop the current parsing so that all that has been parsed so far gets discarded and no code is executed.
The only way I found for now to do this is closing the inputstream used by the parser and recreate the parser. It would be good there was a way do avoid to recreate the parser, but it is at least more lightweight than interrupting the interpreter, the thread etc. 
The only thing we need to do in Interpreter is to make some field protected instead of package so that a subclass can manipulate those objects. I will open a request for this.

**Comment by stefanofornari** [comment]
Ok, I think I managed to do it. See https://github.com/stefanofornari/BshConsole/commit/0d2b1e9da18126ea1aa2df392e498fedd7acb66f for details, but I basically recreated the REPL taking into account:
1. we are always in interactive mode
2. eof may due to Ctrl+C

We can exit the console easily with Ctrl+D

Some tricks where needed because bsh.Interpreter is not very extensions friendly, with many fields with package scope and private method. But at least no changes are actually required to bsh.Interpreter.

I'll wait for comments, than  will close the issue.

**Comment by nickl-** [comment]
> I do think that we are looking at the wrong spot. The whole point is to be able to stop the current parsing so that all that has been parsed so far gets discarded and no code is executed.

You read my explanation on the parser. Yes what you want makes logical sense but no it does not work like that. The only code you can stop from being parsed is anything you typed before pressing enter.
Once you press enter nodes are produces, finish.

> The only way I found for now to do this is closing the inputstream used by the parser and recreate the parser. 

It is only he parser that uses the input, interpreter evaluates the nodes. Closing the input is what produces an EOF and the parser exits.

> It would be good there was a way do avoid to recreate the parser, but it is at least more lightweight than interrupting the interpreter, the thread etc.

I don't follow the logic, with java you want to loose your references as soon as possible so that garbage collector can come and clean up. Remember there are more reasons to to interrupt than just in multi line blocks. For me the most important is being able to got out of long running processes. Then we want to clean up and free memory, don't you agree.

Interpreter was designed to be initialised for every evaruation... have a look at the the ScriptEngine implementation or the interpreter from TestUtil is a good example too.

```java
    public static Object eval(final Map<String, ?> params, final String ... code) throws Exception {
        try (final Interpreter interpreter = new Interpreter()) {
            for (final Map.Entry<String, ?> entry : params.entrySet())
                interpreter.set(entry.getKey(), entry.getValue());
            return interpreter.eval(script(code));
        }
    }
```
We use the static import in the unit tests so every `eval` is a new interpreter.

There are many advantages to dropping old references and restarting the process but I can't think of one benefit to remaining in the REPL loop or the running thread after we reached EOF. What is the point exactly?

Just let those references go and let garbage collector free them up. That's my 2c anyway...

**Comment by nickl-** [comment]
Why are we even still wasting time on this it's been more than a week? When we could be working on completion instead.

I understand perfectly what your vision is, it makes 100% sense. But unfortunately that is not how these components operate. What the parser doesn't understand it will let you know but otherwise it very eagerly chows up what it does. This is actually what makes it better than other approaches. It doesn't matter though because we are using namespace scope so whatever did go into that block scope will not be accessible anymore anyway. Do you follow? Let me see if I can explain:

```
// global scope
a = 4;
doIt() { 
   // method scope
   b = a;  // a can be seen
}
b == void; // b is not accessible from this namespace

doThat() {
  // new method scope
  c = 44; // new variable parsed and value set

^C

// back on global scope so variable c is gone
c == void;
// No need to purge anything
```
 
You are trying to force a square block into a round hole =)

**Comment by stefanofornari** [comment]
As per the code, it works as I explained. look at the code if you still
have doubts ;)
No work is still needed and I am happy about the solution :)

Ste

**Comment by stefanofornari** [comment]
closing

**Comment by nickl-** [comment]
@stefanofornari 
> As per the code, it works as I explained. look at the code if you still have doubts ;)

I did look at the code and I did have questions which you didn't explain. I've only ever tried to help and would never tell you to go look at the code if you have questions.

I also see you ignored all the comments I made about the legacy code which I believe is not necessary. It is obvious my input here is not wanted. Still no hard feelings, my help is given freely yet I don't want to be a bother. Please call my attention with @nickl- at anytime if you need my input here but unless you ask for me I will keep my comments of BshConsole to myself and let you get on with it. 

> No work is still needed and I am happy about the solution :)

You also did it all on your own, didn't need help from anyone, well done man!

It would seem that this is far more important to you then you first lead to believe. You previously offered to donate this work to the BeanShell project, is this still your intention or has the goals for this project changed? Just know that we value your support and will always appreciate your contributions at BeanShell.

**Comment by stefanofornari** [comment]
hi @nickl-, I took this offline.

Ste
